services:
  expressjs-api:
    build: .
    container_name: EXPRESSJS-API
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "${PORT:-3000}:3000"
